include: package:pedantic/analysis_options.yaml

linter:
  rules:
    omit_local_variable_types: false
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true

exclude:
    - lib//*.g.dart
    - lib//*.req.gql.dart