targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|schema_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/helpers/uuid_type.dart'
      gql_build|data_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/helpers/uuid_type.dart'
      gql_build|var_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/helpers/uuid_type.dart'
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          custom_serializers:
          - import: 'package:fe/helpers/uuid_type.dart'
            name: UuidTypeSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
            Date:
              name: DateTime