name: fe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #dev ish dependencies
  bloc: ^7.2.0-dev.1
  flutter_bloc: ^7.2.0-dev.1
  sealed_flutter_bloc: ^7.0.0
  bloc_concurrency: ^0.1.0-dev.2
  sentry_flutter: ^6.2.2
  equatable: ^2.0.3
  get_it: ^7.1.3
  built_collection: ^5.0.0
  shared_preferences: ^2.0.6
  flow_builder: ^0.0.3
  sealed_unions: ^3.0.3+1
  clock: ^1.1.0

  #serialization
  uuid: ^3.0.1
  flutter_secure_storage: ^4.0.0
  path_provider: ^2.0.1
  json_annotation: ^4.0.0
  
  #ui
  flutter_spinkit: ^5.0.0
  flutter_platform_widgets: ^1.9.5
  badges: ^2.0.0-nullsafety.1
  keyboard_attachable: ^2.0.1

  #gql
  ferry: ^0.10.2+2
  gql: ^0.13.0-nullsafety.2
  gql_link: ^0.4.0-nullsafety.3
  gql_http_link: ^0.4.0-nullsafety.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  ferry_hive_store: ^0.4.2
  ferry_flutter: ^0.5.4
  gql_exec: ^0.3.0
  gql_websocket_link: ^0.3.1

  #http
  http: ^0.13.1

  #ws
  web_socket_channel: ^2.1.0

  #other 
  google_sign_in: ^5.0.0
  connectivity: ^3.0.3
  jwt_decoder: ^2.0.1
  intl: ^0.17.0
  provider: ^6.0.0


dev_dependencies:
  #prefs
  pedantic: ^1.11.0

  #builders
  build_runner: ^2.0.4
  json_serializable: ^4.1.0
  ferry_generator: ^0.4.1-0.1.nullsafety.0

  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  fake_async: ^1.2.0
  mocktail: ^0.1.4
  dart_code_metrics: ^4.1.0


flutter:
  uses-material-design: true
  fonts:
    - family: Kontora
      fonts:
        - asset: assets/fonts/Kontora/Kontora-Regular.otf
        - asset: assets/fonts/Kontora/Kontora-Black.otf
          weight: 900
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
          weight: 900
  assets:
    - assets/icons/identities/google_logo.png
    - assets/icons/identities/facebook_logo.png
    - assets/icons/identities/apple_logo.png
    - assets/mock_icons/mock_club_icon.png
