name: fe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #dev ish dependencies
  flutter_bloc: ^7.0.0
  get_it: ^6.0.0
  auto_route: ^1.0.2
  built_collection: ^5.0.0
  

  #serialization
  uuid: ^3.0.1
  flutter_secure_storage: ^4.0.0
  path_provider: ^2.0.1
  json_annotation: ^4.0.0
  
  #ui
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.3
  flutter_platform_widgets: ^1.6.1
  badges: ^2.0.0-nullsafety.1

  #gql
  ferry: ^0.10.1-0.1.nullsafety.0
  gql: ^0.13.0-nullsafety.2
  gql_link: ^0.4.0-nullsafety.3
  gql_error_link: ^0.2.0-nullsafety.1
  gql_transform_link: ^0.2.0-nullsafety.1 
  gql_http_link: ^0.4.0-nullsafety.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  ferry_hive_store: 0.4.1-0.1.nullsafety.0
  fresh_graphql: ^0.5.1
  ferry_flutter: ^0.5.1-0.1.nullsafety.1

  #http
  http: ^0.13.1

  #other 
  google_sign_in: ^5.0.0
  connectivity: ^3.0.3  


dev_dependencies:
  #prefs
  pedantic: ^1.11.0

  #builders
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  auto_route_generator: ^1.0.2
  ferry_generator: ^0.4.1-0.1.nullsafety.0

  #cicd
  dependency_validator: ^3.0.0

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Kontora
      fonts:
        - asset: assets/fonts/Kontora/Kontora-Regular.otf
        - asset: assets/fonts/Kontora/Kontora-Black.otf
          weight: 900
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
          weight: 900
  assets:
    - assets/icons/identities/google_logo.png
    - assets/icons/identities/facebook_logo.png
    - assets/icons/identities/apple_logo.png
    - assets/mock_icons/mock_club_icon.png
    - assets/db.db
