name: fe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #dev ish dependencies
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.3
  sentry_flutter: ^6.2.2
  get_it: ^7.1.3
  built_collection: ^5.0.0
  shared_preferences: ^2.0.6
  flow_builder: ^0.0.3
  clock: ^1.1.0
  image_picker: ^0.8.4+4
  mime: ^1.0.1
  cached_network_image: ^3.2.0
  firebase_messaging: ^11.2.5
  firebase_core: ^1.11.0
  flutter_local_notifications: ^9.2.0
  flutter_app_badger: ^1.3.0
  ical: ^0.2.2
  time_range: ^1.0.2

  #serialization
  uuid: ^3.0.1
  flutter_secure_storage: ^5.0.2
  path_provider: ^2.0.1
  
  #ui
  flutter_spinkit: ^5.0.0
  flutter_platform_widgets: ^1.9.5
  badges: ^2.0.0-nullsafety.1
  keyboard_attachable: ^2.1.0
  table_calendar: ^3.0.3

  #gql
  ferry: ^0.10.2+2
  gql: 0.13.0
  gql_link: ^0.4.0
  gql_http_link: ^0.4.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  ferry_hive_store: ^0.4.2
  ferry_flutter: ^0.5.4
  gql_exec: ^0.3.0
  gql_websocket_link: ^0.3.1

  #http
  http: ^0.13.1

  #ws
  web_socket_channel: ^2.1.0

  #other 
  google_sign_in: ^5.0.0
  connectivity: ^3.0.3
  jwt_decoder: ^2.0.1
  intl: ^0.17.0
  provider: ^6.0.0


dev_dependencies:
  #prefs
  pedantic: ^1.11.0

  #builders
  build_runner: ^2.0.4
  json_serializable: ^4.1.0
  ferry_generator: ^0.4.1-0.1.nullsafety.0

  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.1
  fake_async: ^1.2.0
  mocktail: ^0.2.0
  dart_code_metrics: ^4.1.0


flutter:
  uses-material-design: true
  fonts:
    - family: Kontora
      fonts:
        - asset: assets/fonts/Kontora/Kontora-Regular.otf
        - asset: assets/fonts/Kontora/Kontora-Black.otf
          weight: 900
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
        - asset: assets/fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
          weight: 900
  assets:
    - assets/icons/identities/google_logo.png
    - assets/icons/identities/facebook_logo.png
    - assets/icons/identities/apple_logo.png
    - assets/mock_icons/mock_club_icon.png

