version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: fedormelexin/graphql-engine-arm64:v2.0.0.cli-migrations-v3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: '${ADMIN_SECRET}'
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_METADATA_DIR: /metadata
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256","key": "${JWT_SECRET}"}'
      WEBHOOK_URL: '${WEBHOOK_URL}'
      WEBHOOK_SECRET_KEY: '${WEBHOOK_SECRET_KEY}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'unauthenticated'
    volumes:
      - ./migrations:/migrations
      - ./metadata:/metadata
volumes:
  db_data:

