// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhUVqTCTsObrA6_BfVB9johnNQ5dFGZXc',
    appId: '1:962929179530:web:2fffe275dbc5b7c077a673',
    messagingSenderId: '962929179530',
    projectId: 'club-app-307720',
    authDomain: 'club-app-307720.firebaseapp.com',
    storageBucket: 'club-app-307720.appspot.com',
    measurementId: 'G-FK84V08LS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiaYLM04pX3eX8ZlyRrSYlihGHLpFAiA',
    appId: '1:962929179530:android:42716c48d257fc3277a673',
    messagingSenderId: '962929179530',
    projectId: 'club-app-307720',
    storageBucket: 'club-app-307720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYXB1uYQzMLr-qZiXdA68MpTVsooSjpwo',
    appId: '1:962929179530:ios:42851193f494385677a673',
    messagingSenderId: '962929179530',
    projectId: 'club-app-307720',
    storageBucket: 'club-app-307720.appspot.com',
    androidClientId: '962929179530-tf39tjv7ad8ma8iqihch6b3nooubh9rr.apps.googleusercontent.com',
    iosClientId: '962929179530-qj3o1qkjh1pdu16jcou44m88pi894d4i.apps.googleusercontent.com',
    iosBundleId: 'com.antholeinik.clubapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYXB1uYQzMLr-qZiXdA68MpTVsooSjpwo',
    appId: '1:962929179530:ios:42851193f494385677a673',
    messagingSenderId: '962929179530',
    projectId: 'club-app-307720',
    storageBucket: 'club-app-307720.appspot.com',
    androidClientId: '962929179530-tf39tjv7ad8ma8iqihch6b3nooubh9rr.apps.googleusercontent.com',
    iosClientId: '962929179530-qj3o1qkjh1pdu16jcou44m88pi894d4i.apps.googleusercontent.com',
    iosBundleId: 'com.antholeinik.clubapp',
  );
}
