on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - staging
defaults:
  run:
    working-directory: ./fe
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get
      - name: Run build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage  
      - name: Remove generated
        run: sudo apt-get install -y lcov && make t-clean
      - name: Upload code-cov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/out_cov.info
          flags: unittests
          name: flutter-unit
          fail_ci_if_error: true
          verbose: true
